In [1]:
# simple linear regression
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x = np.array([2, 21, 40, 59, 78, 97]).reshape((-1, 1))
y = np.array([1, 12, 7, 54, 41, 62])

In [3]:
model = LinearRegression()

In [4]:
model.fit(x, y)

model = LinearRegression().fit(x, y)

In [5]:
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")

coefficient of determination: 0.8065496243905501


In [6]:
print(f"intercept: {model.intercept_}")


print(f"slope: {model.coef_}")

intercept: -3.1774436090225606
slope: [0.66015038]


In [9]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print(f"intercept: {new_model.intercept_}")


print(f"slope: {new_model.coef_}")

intercept: [-3.17744361]
slope: [[0.66015038]]


In [10]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[-1.85714286 10.68571429 23.22857143 35.77142857 48.31428571 60.85714286]


In [11]:
y_pred = model.intercept_ + model.coef_ * x
print(f"predicted response:\n{y_pred}")

predicted response:
[[-1.85714286]
 [10.68571429]
 [23.22857143]
 [35.77142857]
 [48.31428571]
 [60.85714286]]


In [13]:
x_new = np.arange(5).reshape((-1, 1))
x_new

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [14]:
y_new = model.predict(x_new)
y_new

array([-3.17744361, -2.51729323, -1.85714286, -1.19699248, -0.53684211])

In [15]:
# multiple linear regression

import numpy as np
from sklearn.linear_model import LinearRegression

x = [
  [0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]
]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [16]:
x

array([[ 0,  1],
       [ 5,  1],
       [15,  2],
       [25,  5],
       [35, 11],
       [45, 15],
       [55, 34],
       [60, 35]])

In [17]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [18]:
model = LinearRegression().fit(x, y)

In [19]:
r_sq = model.score(x, y)
print(f"coefficient of determination: {r_sq}")


print(f"intercept: {model.intercept_}")


print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8615939258756776
intercept: 5.52257927519819
coefficients: [0.44706965 0.25502548]


In [20]:
y_pred = model.predict(x)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [21]:
y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [22]:
x_new = np.arange(10).reshape((-1, 2))
x_new

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
y_new = model.predict(x_new)
y_new

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])

In [24]:
# polynomial regression
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [25]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [26]:
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [27]:
transformer.fit(x)

PolynomialFeatures(include_bias=False)

In [28]:
x_ = transformer.transform(x)

In [29]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [30]:
x_

array([[   5.,   25.],
       [  15.,  225.],
       [  25.,  625.],
       [  35., 1225.],
       [  45., 2025.],
       [  55., 3025.]])

In [31]:
model = LinearRegression().fit(x_, y)

In [32]:
r_sq = model.score(x_, y)
print(f"coefficient of determination: {r_sq}")


print(f"intercept: {model.intercept_}")


print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8908516262498563
intercept: 21.372321428571418
coefficients: [-1.32357143  0.02839286]


In [33]:
x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)

In [34]:
x_

array([[1.000e+00, 5.000e+00, 2.500e+01],
       [1.000e+00, 1.500e+01, 2.250e+02],
       [1.000e+00, 2.500e+01, 6.250e+02],
       [1.000e+00, 3.500e+01, 1.225e+03],
       [1.000e+00, 4.500e+01, 2.025e+03],
       [1.000e+00, 5.500e+01, 3.025e+03]])

In [35]:
model = LinearRegression(fit_intercept=False).fit(x_, y)

In [36]:
r_sq = model.score(x_, y)
print(f"coefficient of determination: {r_sq}")


print(f"intercept: {model.intercept_}")


print(f"coefficients: {model.coef_}")

coefficient of determination: 0.8908516262498564
intercept: 0.0
coefficients: [21.37232143 -1.32357143  0.02839286]


In [37]:
y_pred = model.predict(x_)
print(f"predicted response:\n{y_pred}")

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]
